#You can choose a language file from the list of the languages section in this config.yml right under this option.
lang: english
#Here are all the language file names that you can use, if you use any other file name it can cause errors!
#languages:
# - english
# - chinese
# - french
# - dutch
# - japanese
# - swedish
#The prefix of all messages send by this plugin to a player
plugin-prefix: "&a[Guilds]"

require-money: false
#Requirement:
#  cost: 100
#  sethome-cost: 100
#For some reason the require-money doesn't matter. So here's how this works:
#If you have an economy plugin on your server, uncomment the Requirement and Cost line and set your cost.
#If you are not using an economy plugin but want to make guilds just leave the 2 lines commented above.

#List your server at https://glaremasters.me/server/
server-list: true

updater:
  check: true

name:
# Minimum length of guild names
  min-length: 1
# Maximum length of guild names
  max-length: 64
# RegEx (https://en.wikipedia.org/wiki/Regular_expression) used to only allow certain characters (default only allows alphanumeric characters)
  regex: "^[a-zA-Z0-9]*$"

home:
  cool-down: 60

sethome:
  cool-down: 60

prefix:
# RegEx (https://en.wikipedia.org/wiki/Regular_expression) used to only allow certain characters (default only allows alphanumeric characters)
# With the default Regex currently set, the minimum length of the prefix is 1 and the maximum is 6.
# To change this, adjust the numbers and maybe have a look at the link above.
# When changing the {1,6} you MUST change the "requirements" field under "prefix" down in the config below to the MAX number you have redefined the regex as. E.x. for {1,2} change ("&cYour guild's prefix does not match the requirements! You can only use alphanumeric characters and the length of the prefix cannot exceed 6") to ("&cYour guild's prefix does not match the requirements! You can only use alphanumeric characters and the length of the prefix cannot exceed 2")
  regex: "[a-zA-Z0-9]{1,6}"
# Set the format for the prefix
  format: "&c[{prefix}] "

members:
# Set to -1 to disable
  max-members: 64

chat:
# Enable or disable custom chat formatting for players who are in a guild
  enable: false
# Custom chat format (only applied when the setting above is set to true)
#   - "{guild}" is replaced with the guild prefix
#   - "%s" (First) is replaced with the player's name
#   - "%s" (Second) is replaced with the player's message
  format: "{guild} <%s>: %s"

placeholders:
# Default value for placeholders that don't have a value (Set to "" to leave empty)

#This currently is bugged and will be fixed soon 6-3-2017
  default: "N/A"

scoreboard:
# Enable or disable scoreboard which handles friendly fire, prefixes and guild invisibility
  enable: false
# Enable or disable friendly fire
  friendly-fire: false
# Enable or disable being able to see invisible guild members
  see-invisible: true

database:
# Set the type of the database (Either JSON or MySQL)
  type: JSON
# Uncomment when using MySQL
#  host: "127.0.0.1"
#  port: 3306
#  username: "root"
#  password: "password"
## Note: Database needs to be created manually
#  database: "guilds"
#  pool-size: 10

roles:
  0:
    name: "GuildMaster"
    permissions:
      chat: true
      ally-chat: true
      invite: true
      kick: true
      promote: true
      demote: true
      add-ally: true
      remove-ally: true
      change-prefix: true
      change-home: true
      change-master: true
      remove-guild: true

  1:
    name: "Officer"
    permissions:
      chat: true
      ally-chat: true
      invite: true
      kick: true
      promote: true
      demote: true
      add-ally: true
      remove-ally: true
      change-prefix: false
      change-home: true
      change-master: false
      remove-guild: false

  2:
    name: "Veteran"
    permissions:
      chat: true
      ally-chat: true
      invite: true
      kick: false
      promote: false
      demote: false
      add-ally: false
      remove-ally: false
      change-prefix: false
      change-master: false
      remove-guild: false
  3:
    name: "Member"
    permissions:
      chat: true
      ally-chat: true
      invite: false
      kick: false
      promote: false
      demote: false
      add-ally: false
      remove-ally: false
      change-prefix: false
      change-master: false
      remove-guild: false